[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt --break-system-packages",
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "bash start.sh"